export const COMMON_NCD_MEDICATIONS = [
  { name: "Amlodipine", generic: "Amlodipine", dosages: ["2.5mg", "5mg", "10mg"], purpose: "blood_pressure", category: "CCB" },
  { name: "Telmisartan", generic: "Telmisartan", dosages: ["20mg", "40mg", "80mg"], purpose: "blood_pressure", category: "ARB" },
  { name: "Losartan", generic: "Losartan", dosages: ["25mg", "50mg", "100mg"], purpose: "blood_pressure", category: "ARB" },
  { name: "Enalapril", generic: "Enalapril", dosages: ["5mg", "10mg", "20mg"], purpose: "blood_pressure", category: "ACEI" },
  { name: "Ramipril", generic: "Ramipril", dosages: ["2.5mg", "5mg", "10mg"], purpose: "blood_pressure", category: "ACEI" },
  { name: "Hydrochlorothiazide", generic: "HCTZ", dosages: ["12.5mg", "25mg"], purpose: "blood_pressure", category: "Diuretic" },
  { name: "Atenolol", generic: "Atenolol", dosages: ["25mg", "50mg", "100mg"], purpose: "blood_pressure", category: "Beta Blocker" },
  { name: "Clinidipine", generic: "Clinidipine", dosages: ["5mg", "10mg"], purpose: "blood_pressure", category: "CCB" },
  { name: "Metformin", generic: "Metformin", dosages: ["250mg", "500mg", "850mg", "1000mg"], purpose: "blood_sugar", category: "Biguanide" },
  { name: "Glimepiride", generic: "Glimepiride", dosages: ["1mg", "2mg", "3mg", "4mg"], purpose: "blood_sugar", category: "Sulfonylurea" },
  { name: "Glipizide", generic: "Glipizide", dosages: ["5mg", "10mg"], purpose: "blood_sugar", category: "Sulfonylurea" },
  { name: "Sitagliptin", generic: "Sitagliptin", dosages: ["50mg", "100mg"], purpose: "blood_sugar", category: "DPP-4 Inhibitor" },
  { name: "Voglibose", generic: "Voglibose", dosages: ["0.2mg", "0.3mg"], purpose: "blood_sugar", category: "Alpha-glucosidase Inhibitor" },
  { name: "Empagliflozin", generic: "Empagliflozin", dosages: ["10mg", "25mg"], purpose: "blood_sugar", category: "SGLT2 Inhibitor" },
  { name: "Dapagliflozin", generic: "Dapagliflozin", dosages: ["5mg", "10mg"], purpose: "blood_sugar", category: "SGLT2 Inhibitor" },
  { name: "Pioglitazone", generic: "Pioglitazone", dosages: ["15mg", "30mg"], purpose: "blood_sugar", category: "Thiazolidinedione" },
  { name: "Atorvastatin", generic: "Atorvastatin", dosages: ["10mg", "20mg", "40mg"], purpose: "cholesterol", category: "Statin" },
  { name: "Rosuvastatin", generic: "Rosuvastatin", dosages: ["5mg", "10mg", "20mg"], purpose: "cholesterol", category: "Statin" },
  { name: "Aspirin", generic: "Aspirin", dosages: ["75mg", "150mg"], purpose: "heart", category: "Antiplatelet" },
  { name: "Clopidogrel", generic: "Clopidogrel", dosages: ["75mg"], purpose: "heart", category: "Antiplatelet" },
];
